[project]
name = "practice-async-or-sync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "agents>=1.4.0",
    "dotenv>=0.9.9",
    "openai-agents>=0.0.16",
]
