[project]
name = "hg-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "chainlit>=2.3.0",
    "docx>=0.2.4",
    "dox>=0.2.0",
    "openai-agents>=0.0.16",
    "pypdf2>=3.0.1",
]
